# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          # login-server: https://registry.us-west-1.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password:  ${{ secrets.ACR_PASSWORD }}

      - name: Push to Docker Registry
        run: |
      - name: Push to Docker Registry
        run: |
          # docker pull quay.io/minio/minio:RELEASE.2022-09-17T00-09-45Z
          # REGISTRY="registry.cn-hangzhou.aliyuncs.com/wkmx"
          
          # docker pull grafana/loki-canary:3.0.0

          
          # docker tag grafana/loki-canary:3.0.0 ${REGISTRY}/loki-canary:3.0.0

          # docker push ${REGISTRY}/loki-canary:3.0.0

          
          docker pull golang:1.25.0-alpine3.22

          docker tag golang:1.25.0-alpine3.22 registry.cn-hangzhou.aliyuncs.com/wkmx/golang:1.25.0-alpine3.22

          docker push registry.cn-hangzhou.aliyuncs.com/wkmx/golang:1.25.0-alpine3.22

