# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password:  ${{ secrets.ACR_PASSWORD }}

      - name: Push to Docker Registry
        run: |
      - name: Push to Docker Registry
        run: |
          # docker pull quay.io/minio/minio:RELEASE.2022-09-17T00-09-45Z
          REGISTRY="registry.cn-hangzhou.aliyuncs.com/wkmx"

          docker pull mysql:8.1.0
          docker pull quay.io/prometheus/node-exporter:v1.7.0
          docker pull "docker.io/library/busybox:1.31.1"
          docker pull "quay.io/kiwigrid/k8s-sidecar:1.25.2"
          docker pull "quay.io/kiwigrid/k8s-sidecar:1.25.2"
          docker pull "docker.io/grafana/grafana:10.2.3"
          docker pull docker.io/wkmx/kube-state-metrics:v2.10.1
          docker pull "quay.io/prometheus-operator/prometheus-operator:v0.70.0"
          docker pull "quay.io/prometheus/alertmanager:v0.26.0"
          docker pull "quay.io/prometheus/prometheus:v2.48.1"
          docker pull "docker.io/bats/bats:v1.4.1"
          docker pull docker.io/wkmx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6

          docker tag quay.io/prometheus/node-exporter:v1.7.0 ${REGISTRY}/node-exporter:v1.7.0
          docker tag "docker.io/library/busybox:1.31.1" ${REGISTRY}/busybox:1.31.1
          docker tag "quay.io/kiwigrid/k8s-sidecar:1.25.2" ${REGISTRY}/k8s-sidecar:1.25.2
          docker tag "docker.io/grafana/grafana:10.2.3" ${REGISTRY}/grafana:10.2.3
          docker tag docker.io/wkmx/kube-state-metrics:v2.10.1 ${REGISTRY}/kube-state-metrics:v2.10.1
          docker tag "quay.io/prometheus-operator/prometheus-operator:v0.70.0" ${REGISTRY}/prometheus-operator:v0.70.0
          docker tag "quay.io/prometheus/alertmanager:v0.26.0" ${REGISTRY}/alertmanager:v0.26.0
          docker tag "quay.io/prometheus/prometheus:v2.48.1" ${REGISTRY}/prometheus:v2.48.1
          docker tag "docker.io/bats/bats:v1.4.1" ${REGISTRY}/bats:v1.4.1
          docker tag docker.io/wkmx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6 ${REGISTRY}/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6

          docker push ${REGISTRY}/node-exporter:v1.7.0
          docker push ${REGISTRY}/busybox:1.31.1
          docker push ${REGISTRY}/k8s-sidecar:1.25.2
          docker push ${REGISTRY}/grafana:10.2.3
          docker push ${REGISTRY}/kube-state-metrics:v2.10.1
          docker push ${REGISTRY}/prometheus-operator:v0.70.0
          docker push ${REGISTRY}/alertmanager:v0.26.0
          docker push ${REGISTRY}/prometheus:v2.48.1
          docker push ${REGISTRY}/bats:v1.4.1
          docker push ${REGISTRY}/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6


