# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/kubectl:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-exporter:14.3.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-shell:v14.34.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-kas:v16.10.1
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ee:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-container-registry:v3.90.0-gitlab
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitaly:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/kubectl:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0
          docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v16.10.0

          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee:v16.10.0 wkmx/gitlab-webservice-ee:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/kubectl:v16.10.0 wkmx/kubectl:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-exporter:14.3.0 wkmx/gitlab-exporter:14.3.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-shell:v14.34.0 wkmx/gitlab-shell:v14.34.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-kas:v16.10.1 wkmx/gitlab-kas:v16.10.1
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee:v16.10.0 wkmx/gitlab-sidekiq-ee:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee:v16.10.0 wkmx/gitlab-sidekiq-ee:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v16.10.0 wkmx/gitlab-toolbox-ee:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee:v16.10.0 wkmx/gitlab-webservice-ee:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee:v16.10.0 wkmx/gitlab-webservice-ee:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ee:v16.10.0 wkmx/gitlab-workhorse-ee:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-container-registry:v3.90.0-gitlab wkmx/gitlab-container-registry:v3.90.0-gitlab
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitaly:v16.10.0 wkmx/gitaly:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/kubectl:v16.10.0 wkmx/kubectl:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/certificates:v16.10.0 wkmx/certificates:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v16.10.0 wkmx/gitlab-base:v16.10.0
          docker tag registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v16.10.0 wkmx/gitlab-toolbox-ee:v16.10.0


      - name: Login in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Registry
        run: |
          docker push wkmx/gitlab-webservice-ee:v16.10.0
          docker push wkmx/kubectl:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/gitlab-exporter:14.3.0
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/gitlab-shell:v14.34.0
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-kas:v16.10.1
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/gitlab-sidekiq-ee:v16.10.0
          docker push wkmx/gitlab-sidekiq-ee:v16.10.0
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/gitlab-toolbox-ee:v16.10.0
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/gitlab-webservice-ee:v16.10.0
          docker push wkmx/gitlab-webservice-ee:v16.10.0
          docker push wkmx/gitlab-workhorse-ee:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/gitlab-container-registry:v3.90.0-gitlab
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/gitaly:v16.10.0
          docker push wkmx/kubectl:v16.10.0
          docker push wkmx/certificates:v16.10.0
          docker push wkmx/gitlab-base:v16.10.0
          docker push wkmx/gitlab-toolbox-ee:v16.10.0
