# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          # login-server: https://registry.cn-hangzhou.aliyuncs.com
          login-server: https://registry.us-west-1.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password:  ${{ secrets.ACR_PASSWORD }}

      - name: Push to Docker Registry
        run: |
      - name: Push to Docker Registry
        run: |
          # docker pull quay.io/minio/minio:RELEASE.2022-09-17T00-09-45Z
          # REGISTRY="registry.cn-hangzhou.aliyuncs.com/wkmx"
          
          # docker pull grafana/loki-canary:3.0.0

          
          # docker tag grafana/loki-canary:3.0.0 ${REGISTRY}/loki-canary:3.0.0

          # docker push ${REGISTRY}/loki-canary:3.0.0


          
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/cni:v3.27.3
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/coredns:1.9.3
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/k8s-dns-node-cache:1.22.20
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/kube-apiserver:v1.28.8
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/kube-controller-manager:v1.28.8
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/kube-controllers:v3.27.3
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/kube-proxy:v1.28.8
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/kube-scheduler:v1.28.8
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/nacos-peer-finder-plugin:1.1
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/nacos-server:v2.2.0
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/node-exporter:v1.7.0
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/node:v3.27.3
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/pause:3.9
          docker pull registry.cn-hangzhou.aliyuncs.com/wkmx/promtail:2.9.3
          
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/cni:v3.27.3	registry.us-west-1.aliyuncs.com/wkmx/cni:v3.27.3
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/coredns:1.9.3	registry.us-west-1.aliyuncs.com/wkmx/coredns:1.9.3
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/k8s-dns-node-cache:1.22.20	registry.us-west-1.aliyuncs.com/wkmx/k8s-dns-node-cache:1.22.20
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/kube-apiserver:v1.28.8	registry.us-west-1.aliyuncs.com/wkmx/kube-apiserver:v1.28.8
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/kube-controller-manager:v1.28.8	registry.us-west-1.aliyuncs.com/wkmx/kube-controller-manager:v1.28.8
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/kube-controllers:v3.27.3	registry.us-west-1.aliyuncs.com/wkmx/kube-controllers:v3.27.3
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/kube-proxy:v1.28.8	registry.us-west-1.aliyuncs.com/wkmx/kube-proxy:v1.28.8
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/kube-scheduler:v1.28.8	registry.us-west-1.aliyuncs.com/wkmx/kube-scheduler:v1.28.8
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/nacos-peer-finder-plugin:1.1	registry.us-west-1.aliyuncs.com/wkmx/nacos-peer-finder-plugin:1.1
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/nacos-server:v2.2.0	registry.us-west-1.aliyuncs.com/wkmx/nacos-server:v2.2.0
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/node-exporter:v1.7.0	registry.us-west-1.aliyuncs.com/wkmx/node-exporter:v1.7.0
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/node:v3.27.3	registry.us-west-1.aliyuncs.com/wkmx/node:v3.27.3
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/pause:3.9	registry.us-west-1.aliyuncs.com/wkmx/pause:3.9
          docker tag registry.cn-hangzhou.aliyuncs.com/wkmx/promtail:2.9.3	registry.us-west-1.aliyuncs.com/wkmx/promtail:2.9.3
          
          
          docker push registry.us-west-1.aliyuncs.com/wkmx/cni:v3.27.3
          docker push registry.us-west-1.aliyuncs.com/wkmx/coredns:1.9.3
          docker push registry.us-west-1.aliyuncs.com/wkmx/k8s-dns-node-cache:1.22.20
          docker push registry.us-west-1.aliyuncs.com/wkmx/kube-apiserver:v1.28.8
          docker push registry.us-west-1.aliyuncs.com/wkmx/kube-controller-manager:v1.28.8
          docker push registry.us-west-1.aliyuncs.com/wkmx/kube-controllers:v3.27.3
          docker push registry.us-west-1.aliyuncs.com/wkmx/kube-proxy:v1.28.8
          docker push registry.us-west-1.aliyuncs.com/wkmx/kube-scheduler:v1.28.8
          docker push registry.us-west-1.aliyuncs.com/wkmx/nacos-peer-finder-plugin:1.1
          docker push registry.us-west-1.aliyuncs.com/wkmx/nacos-server:v2.2.0
          docker push registry.us-west-1.aliyuncs.com/wkmx/node-exporter:v1.7.0
          docker push registry.us-west-1.aliyuncs.com/wkmx/node:v3.27.3
          docker push registry.us-west-1.aliyuncs.com/wkmx/pause:3.9
          docker push registry.us-west-1.aliyuncs.com/wkmx/promtail:2.9.3
