# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          docker pull registry.k8s.io/ingress-nginx/controller:v1.10.0
          docker pull registry.k8s.io/ingress-nginx/opentelemetry:v20230721-3e2062ee5
          docker pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.1
          docker pull registry.k8s.io/defaultbackend-amd64:1.5
          docker pull registry.k8s.io/busybox:latest
          
          
          docker tag registry.k8s.io/ingress-nginx/controller:v1.10.0  registry.cn-hangzhou.aliyuncs.com/wkmx/ingress-nginx-controller:v1.10.0 
          docker tag registry.k8s.io/ingress-nginx/opentelemetry:v20230721-3e2062ee5  registry.cn-hangzhou.aliyuncs.com/wkmx/ingress-nginx-opentelemetry:v20230721-3e2062ee5 
          docker tag registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.1  registry.cn-hangzhou.aliyuncs.com/wkmx/ingress-nginx-kube-webhook-certgen:v1.4.1 
          docker tag registry.k8s.io/defaultbackend-amd64:1.5  registry.cn-hangzhou.aliyuncs.com/wkmx/defaultbackend-amd64:1.5 
          docker tag registry.k8s.io/busybox:latest  registry.cn-hangzhou.aliyuncs.com/wkmx/busybox:latest 

          
      - name: Login in to Docker Hub
        # uses: docker/login-action@v3
        uses: aliyun/acr-login@v1
        with:
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          login-server: https://registry.cn-hangzhou.aliyuncs.com
      - name: Push to Docker Registry
          docker push registry.cn-hangzhou.aliyuncs.com/wkmx/ingress-nginx-controller:v1.10.0 
          docker push registry.cn-hangzhou.aliyuncs.com/wkmx/ingress-nginx-opentelemetry:v20230721-3e2062ee5 
          docker push registry.cn-hangzhou.aliyuncs.com/wkmx/ingress-nginx-kube-webhook-certgen:v1.4.1 
          docker push registry.cn-hangzhou.aliyuncs.com/wkmx/defaultbackend-amd64:1.5 
          docker push registry.cn-hangzhou.aliyuncs.com/wkmx/busybox:latest 
